### ISSUE TITLE
License is missing

### ISSUE THREAD

**Issue by yagnasrinath** [bachp/bacnet-rs#2]
@bachp Thank you for our work on adding infrastructure. We are interested in maintaining this repo. But having no license prevents us from doing so. Would you please consider adding a license like MIT or a BSD. Thanks!

**Comment by bachp** [comment]
@yagnasrinath Thanks for pointing this out. The library is dual licensed MIT/Apache-2.0. I added the missing license files.

Looking forward to your contributions.

**Comment by yagnasrinath** [comment]
Thank you very much for prompt response. Looking forward to it
